# Generated by Django 4.0.1 on 2022-02-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_skills_description_skills_descriptioen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='descriptioen',
            new_name='description',
        ),
    ]
