# Generated by Django 4.1.4 on 2023-01-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_message'),
        ('projects', '0009_alter_project_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
