# Generated by Django 4.1.4 on 2023-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='DSCN7891.JPG', null=True, upload_to=''),
        ),
    ]
